#ifndef REN_GLSL_INTERFACE_H
#define REN_GLSL_INTERFACE_H

#include "common.h"

REN_NAMESPACE_BEGIN

const uint NUM_SAMPLED_TEXTURES = 1024;
const uint NUM_STORAGE_TEXTURES = 1024;

const uint PERSISTENT_SET = 0;
const uint SAMPLED_TEXTURES_SLOT = 0;
const uint STORAGE_TEXTURES_SLOT = 1;

REN_NAMESPACE_END

#endif // REN_GLSL_INTERFACE_H
