#ifndef REN_GLSL_INTERFACE_GLSL
#define REN_GLSL_INTERFACE_GLSL

#include "interface.h"

#define TEXTURES \
SAMPLER2D(PERSISTENT_SET, SAMPLED_TEXTURES_SLOT) g_textures2d[NUM_SAMPLED_TEXTURES]; \
IMAGE2D(PERSISTENT_SET, STORAGE_TEXTURES_SLOT, restrict) g_rwimages2d[NUM_STORAGE_TEXTURES]; \
IMAGE2D(PERSISTENT_SET, STORAGE_TEXTURES_SLOT, restrict readonly) g_rimages2d[NUM_STORAGE_TEXTURES];

#endif // REN_GLSL_INTERFACE_GLSL
