#ifndef REN_GLSL_LUMINANCE_HISTOGRAM_H
#define REN_GLSL_LUMINANCE_HISTOGRAM_H

#include "common.h"

REN_NAMESPACE_BEGIN

const float MIN_LUMINANCE = 1.0f / 65536.0f;
const float MIN_LOG_LUMINANCE = log2(MIN_LUMINANCE);
const float MAX_LOG_LUMINANCE = 16.0f;
const uint NUM_LUMINANCE_HISTOGRAM_BINS = 64;

REN_BUFFER_REFERENCE(4) LuminanceHistogram {
  uint bins[NUM_LUMINANCE_HISTOGRAM_BINS];
};

REN_NAMESPACE_END

#endif // REN_GLSL_LUMINANCE_HISTOGRAM_H
