#pragma once
#include "Formats.inl"

#include <dxgiformat.h>

namespace ren {
REN_MAP_TYPE(Format, DXGI_FORMAT);
REN_MAP_FIELD(Format::RGBA8, DXGI_FORMAT_R8G8B8A8_UNORM);
REN_MAP_FIELD(Format::RGBA8_SRGB, DXGI_FORMAT_R8G8B8A8_UNORM_SRGB);
REN_MAP_FIELD(Format::BGRA8, DXGI_FORMAT_B8G8R8A8_UNORM);
REN_MAP_FIELD(Format::BGRA8_SRGB, DXGI_FORMAT_B8G8R8A8_UNORM_SRGB);
REN_MAP_FIELD(Format::RGBA16F, DXGI_FORMAT_R16G16B16A16_FLOAT);

REN_MAP_ENUM(getDXGIFormat, Format, REN_FORMATS);
REN_REVERSE_MAP_ENUM(getFormat, Format, REN_FORMATS);
} // namespace ren
