#ifndef REN_GLSL_CALCULATE_NORMAL_MATRICES_H
#define REN_GLSL_CALCULATE_NORMAL_MATRICES_H

#include "DevicePtr.h"
#include "Std.h"

GLSL_NAMESPACE_BEGIN

const uint CALCULATE_NORMAL_MATRICES_THREADS = 128;

GLSL_PUSH_CONSTANTS CalculateNormalMatricesArgs {
  GLSL_READONLY GLSL_PTR(mat4x3) transforms;
  GLSL_WRITEONLY GLSL_PTR(mat3) normals;
}
GLSL_PC;

GLSL_NAMESPACE_END

#endif // REN_GLSL_CALCULATE_NORMAL_MATRICES_H
