#ifndef REN_GLSL_GPU_SCENE_H
#define REN_GLSL_GPU_SCENE_H

#include "Common.h"

GLSL_NAMESPACE_BEGIN

#define GLSL_MESH_INSTANCE_VISIBILITY_MASK uint32_t
const uint MESH_INSTANCE_VISIBILITY_MASK_SIZE = 4;
static_assert(sizeof(GLSL_MESH_INSTANCE_VISIBILITY_MASK) ==
              MESH_INSTANCE_VISIBILITY_MASK_SIZE);
const uint MESH_INSTANCE_VISIBILITY_MASK_BIT_SIZE =
    MESH_INSTANCE_VISIBILITY_MASK_SIZE * 8;

GLSL_NAMESPACE_END

#endif // REN_GLSL_GPU_SCENE_H
