#pragma once
#include "InstanceCullingAndLOD.h"

GLSL_NAMESPACE_BEGIN

GLSL_PUSH_CONSTANTS(GLSL_INSTANCE_CULLING_AND_LOD_CONSTANTS,
                    InstanceCullingAndLODConstants);

GLSL_NAMESPACE_END

#undef GLSL_INSTANCE_CULLING_CONSTANTS
