#pragma once
#include "InstanceCulling.h"

GLSL_NAMESPACE_BEGIN

GLSL_PUSH_CONSTANTS(GLSL_INSTANCE_CULLING_CONSTANTS, InstanceCullingConstants);

GLSL_NAMESPACE_END

#undef GLSL_INSTANCE_CULLING_CONSTANTS
