#include "MeshletSorting.h"

LOCAL_SIZE(MESHLET_SORTING_THREADS);
void main() {
  uint num_commands = min(DEREF(pc.num_commands), MAX_DRAW_MESHLETS);
  if (gl_GlobalInvocationID.x >= num_commands) {
    return;
  }
  glsl_BatchId batch = DEREF(pc.unsorted_command_batch_ids[gl_GlobalInvocationID.x]);
  uint offset = atomicAdd(DEREF(pc.batch_out_offsets[batch]), 1);
  DEREF(pc.commands[offset]) = DEREF(pc.unsorted_commands[gl_GlobalInvocationID.x]);
}
