#ifndef REN_GLSL_TEXTURES_H
#define REN_GLSL_TEXTURES_H

#include "Common.h"

GLSL_NAMESPACE_BEGIN

const uint NUM_SAMPLED_TEXTURES = 1024;
const uint NUM_STORAGE_TEXTURES = 1024;

const uint SAMPLED_TEXTURES_SLOT = 0;
const uint STORAGE_TEXTURES_SLOT = 1;

GLSL_NAMESPACE_END

#endif // REN_GLSL_TEXTURES_H
